export const PROGRESS_LS_KEY = "progress";

export const questIds: Record<string, string | undefined> = {
  "Kaer Morhen": "0",
  "Lilac and Gooseberries Part 1": "1",
  "Twisted Firestarter": "2",
  "A Frying Pan, Spick and Span": "3",
  "Precious Cargo": "4",
  "Missing in Action": "5",
  "Devil by the Well": "6",
  "On Death's Bed": "7",
  "The Beast of White Orchard": "8",
  "Lilac and Gooseberries Part 2": "9",
  "The Incident at White Orchard": "10",
  "Dirty Funds": "11",
  "Deserter Gold": "12",
  "Temerian Valuables": "13",
  "Viper Silver Sword (Basic)": "14",
  "Viper Steel Sword (Basic)": "15",
  "Gwent: Collect 'em All! (White Orchard)": "16",
  "Imperial Audience": "17",
  "Gwent: Collect 'em All! (Vizima)": "18",
  "Funeral Pyres": "19",
  "At the Mercy of Strangers Part 1": "20",
  "The Nilfgaardian Connection": "21",
  "Looters (I)": "22",
  "Man's Best Friend": "23",
  "Deadly Crossing (II)": "24",
  "Hazardous Goods": "25",
  "Caravan Attack": "26",
  "Harassing a Troll": "27",
  "Face Me if You Dare (I)": "28",
  "Bloody Baron": "29",
  "Ciri's Story: The King of the Wolves": "30",
  "Family Matters Part 1": "31",
  "Ciri's Room": "32",
  "The Mysterious Passenger": "33",
  "Deadly Crossing (I)": "34",
  "Deadly Crossing (III)": "35",
  "Highway Robbery": "36",
  "Highwayman's Cache": "37",
  "A Princess in Distress": "38",
  "Crow's Perch Fight": "39",
  "Thou Shalt Not Pass": "40",
  "Death By Fire": "41",
  "Looters (II)": "42",
  "Lynch Mob": "43",
  "Ciri's Story: The Race": "44",
  "Hunting a Witch": "45",
  "Wandering in the Dark": "46",
  "Magic Lamp": "47",
  "Races: Crow's Perch": "48",
  "An Invitation from Keira Metz": "49",
  "A Towerful of Mice": "50",
  "A Favor for a Friend": "51",
  "For the Advancement of Learning": "52",
  "Defender of the Faith": "53",
  "A Dog's Life": "54",
  "The Fall of the House of Reardon": "55",
  "Ghosts of the Past": "56",
  "Gwent: Velen Players": "57",
  "Looters (III)": "58",
  "Ladies of the Wood": "59",
  "The Whispering Hillock": "60",
  "Ciri's Story: Fleeing the Bog": "61",
  "Family Matters (Part 2)": "62",
  "Ciri's Story: Out of the Shadows": "63",
  "In Ciri's Footsteps: Velen": "64",
  "Return to Crookback Bog": "65",
  "Saving Farmer's Daughter From Soldiers (I)": "66",
  "Saving Farmer's Daughter From Soldiers (II)": "67",
  "Bitter Harvest": "68",
  "Fake Papers": "69",
};
